apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "md-reader.fullname" . }}-backend-memory
  labels:
    {{- include "md-reader.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backend.persistence.memory.storageClass }}
  storageClassName: {{ .Values.backend.persistence.memory.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.memory.size | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "md-reader.fullname" . }}-backend-output
  labels:
    {{- include "md-reader.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backend.persistence.output.storageClass }}
  storageClassName: {{ .Values.backend.persistence.output.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.output.size | quote }}
