apiVersion: v1
kind: Service
metadata:
  name: {{ include "md-reader.backend.serviceName" . }}
  labels:
    {{- include "md-reader.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "md-reader.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
