apiVersion: v1
kind: Secret
metadata:
  name: {{ include "md-reader.fullname" . }}-secret
  labels:
    {{- include "md-reader.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.backend.secrets.openaiApiKey | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.backend.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.secrets.awsSecretAccessKey | quote }}
